Smile 970 integrasjon mot instservice
BIBSYSDEV/InterLibraryLoanMetadata-api pull request #11
Opened 2021-09-06 09:41 UTC by gregorgabriel

2021-09-07 09:00 UTC, anetteOlli requested changes

2021-09-07 09:00 UTC, anetteOlli commented on build.gradle
> +    implementation group: 'org.slf4j', name: 'slf4j-api', version: '1.7.32'
aws logger istedet?

2021-09-07 09:00 UTC, anetteOlli commented on src/main/java/no/unit/ill/services/InstitutionServiceConnection.java
> +public class InstitutionServiceConnection {
Kan denne klassen skrives mer generell så kan også pnx hentes vha. denne?

2021-09-07 12:37 UTC, nraanes commented on src/main/java/no/unit/ill/services/InstitutionServiceConnection.java
> +public class InstitutionServiceConnection {
Kan sikkert brukes til connection mot BaseBibliotek også hvis den er generell

2021-09-08 06:23 UTC, gregorgabriel commented on build.gradle
> +    implementation group: 'org.slf4j', name: 'slf4j-api', version: '1.7.32'
Da har du rett i. Det skal jeg fikse.

2021-09-08 06:26 UTC, gregorgabriel commented on src/main/java/no/unit/ill/services/InstitutionServiceConnection.java
> +public class InstitutionServiceConnection {
Dere er ekte plynderer. Koden er ikke en gang jaktet, men dere deler allerede bytte.

2021-09-08 12:26 UTC, gregorgabriel commented on build.gradle
> +    implementation group: 'org.slf4j', name: 'slf4j-api', version: '1.7.32'
Ok, etter litt etterforsking og snakk med Orestis (arkitekt) beholder vi slf4j.

2021-09-08 12:37 UTC, nraanes approved these changes

2021-09-08 12:39 UTC, merged